<h1>Homework 2</h1>
In this notebook there are the activities related to the second homework and, as with the first homework, feel free to use the web to find the solutions to any of these problems. Also, the bonus questions are not mandatory but, if you happen to have the time, try them out too!<br>



<h1>numpy</h1>
Exercise 1: show that now you can import libraries by importing pandas, numpy and matplotlib.

In [163]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sys

Exercise 2: Will the following code block work?  

In [40]:
# This creates a 3x3 array of random numbers ranging from 1 to 100
array1 = np.round_((np.random.random((3, 3)))*100)

#Second one creates a 3 x 1 array of random mumbers from 1 to 100
array2 = np.round_((np.random.random((3, 1)))*100)

print(array1)
print(array2)

#Adds the values of 3x1 array to the values of each colomn of the 3x3 array
print(np.add(array1,array2))

[[ 3. 59. 93.]
 [39. 58. 21.]
 [20. 22. 49.]]
[[64.]
 [60.]
 [30.]]
[[ 67. 123. 157.]
 [ 99. 118.  81.]
 [ 50.  52.  79.]]


Exercise 3: What about now?

In [393]:
# This creates a 3x3 array of random numbers ranging from 1 to 100
array3 = np.round_((np.random.random((3, 3)))*100)
array4 = np.round_((np.random.random((3, 2)))*100)

# np.add(array3,array4)

#3x2 array can not be added to 3x3 array 

Exercise 4: by inspecting the arrays 1 to 4 can you figure out why one operation worked and another one didn't? (hint: check their values and shape)

In [ ]:
#Exercise 1:  Adds the values of 3x1 array to the values of each colomn of the 3x3 array
#Exercise 2: 3x2 array can not be added to 3x3 array 

Exercise 5: Using the function to create an array of random numbers [np.random.random](https://numpy.org/doc/stable/reference/random/generated/numpy.random.random.html) how can you modify the code (as in the cells above) so that the numbers will vary between 0 and 100 instead of 0 and 1? And how can you modify the shape of the function?

In [58]:
#I multiplyed the result by 100 and rounded it. 
#To change the shape of the array, manipulate the arguments of the np.random.random() function. First number is rows, second is columns
array5 = np.round_((np.random.random((2, 5)))*100)

array6 = np.round_((np.random.random((4, 2)))*100)

print(array5)
print(array6)

[[58. 95. 66. 21. 37.]
 [45.  6. 65. 80. 27.]]
[[ 3. 31.]
 [12. 22.]
 [69. 19.]
 [67. 35.]]


Exercise 6: Using the array defined on the exercise above, use [np.where](https://numpy.org/doc/stable/reference/generated/numpy.where.html) to find the positions the values that are larger than 50 (or feel free to pick any other number).

In [62]:
print(np.where(array5>50))
print(np.where(array6>50))

(array([0, 0, 0, 1, 1]), array([0, 1, 2, 2, 3]))
(array([2, 3]), array([0, 0]))


<h1>Pandas </h1>
There are two datasets on available to this work one is the pokemon dataset we explored in the lectured and the other one is the same dataframe but, for the sake of a nice story, let us say it was sabotaged by team rocket.

Exercise 1: open both dataframes supplied using [pd.read_csv](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html) (and don't forget to assign them to different objects).

In [169]:
pokemon_df = pd.read_csv("./Pokemon.csv")
sabotaged_pokemon_df = pd.read_csv("./Pokemon_sabotage.csv")

Exercise 2: Using [pd.isna](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.isna.html) check how many missing numbers are in each dataframe.

In [392]:
# print(missing_df.value_counts(['Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
#        'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary']))
#2
print(pokemon_df.isna().sum().sum(),"cells are empty in original file")
print(sabotaged_pokemon_df.isna().sum().sum(), "cells are empty in damaged file")



386 cells are empty in original file
399 cells are empty in damaged file


Exercise 3: Two of the main ways to deal with missing data is [pd.dropna](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dropna.html) and [pd.fillna](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.fillna.html). How are these methods different from each other in how they deal with the missing data? Which, if any, would you use on the dataset? Why?

In [ ]:
#pd.dropna will delete columns or rows that contain NaN, pd.fillna would fill the missing cells with set values pd.fillna(0) for numbers or pd.fillna("missing") for strings
#I am not sure on this one.... My guess would be to fill them with preset values. 
#When we drop, do we drop the cells with data too?

From now on we will only be working with the main (non sabotaged dataframe).<br>

Exercise 4: to free up memory delete the sabotaged dataframe. Bonus: before deleting find a way to check how much space in memory the dataframes occupy. [hint](https://stackoverflow.com/questions/449560/how-do-i-determine-the-size-of-an-object-in-python)

In [191]:
print(sys.getsizeof(pokemon_df))
print(sys.getsizeof(sabotaged_pokemon_df), "(bytes ?) was deleted") 
del sabotaged_pokemon_df

199405
199279 (bytes ?) was deleted


Exercise 5: Create a new column that contains the sum of the Attack, speed and defense stats.

In [200]:
pokemon_df['Atk + Spd + Def'] = pokemon_df['HP'] + pokemon_df["Attack"] +pokemon_df['Defense'] + pokemon_df["Speed"]
pokemon_df[["Name", 'Atk + Spd + Def']]

Name  Atk + Spd + Def
0                Bulbasaur              188
1                  Ivysaur              245
2                 Venusaur              325
3    VenusaurMega Venusaur              383
4               Charmander              199
..                     ...              ...
795                Diancie              350
796    DiancieMega Diancie              430
797    HoopaHoopa Confined              320
798     HoopaHoopa Unbound              380
799              Volcanion              380

[800 rows x 2 columns]

Exercise 6: Find out the mean value of the attack, speed, defense columns and the new column that was created above.

In [218]:
pokemon_df[["Attack", "Defense", "Speed", "Atk + Spd + Def"]].mean()

Attack              79.00125
Defense             73.84250
Speed               68.27750
Atk + Spd + Def    290.38000
dtype: float64

Exercise 7: Find out how many pokemon have above average stats in the attack, speed, defense and the new column. Bonus: Do the pokemon with above average stats have a preffered type?

In [389]:
#=================
#Define mean stats

#Couldn't figure out how to compare it to one entity rather than creating a separate variables.
#=================
avg_attack = pokemon_df["Attack"].mean()
avg_speed = pokemon_df["Speed"].mean()
avg_defence = pokemon_df["Defense"].mean()
avg_combine = pokemon_df["Atk + Spd + Def"].mean()
#==============================
#Print mean stats
#==============================
print(f"Average:\n-----------------------------\n{avg}\n-----------------------------")

#===================================
#Filter by stats bigger than average
#===================================
filtered_df = pokemon_df[(pokemon_df['Attack'] > avg_attack) & (pokemon_df['Speed'] > avg_speed) & (pokemon_df['Defense'] > avg_defence) & (pokemon_df["Atk + Spd + Def"] > avg_combine)]
#=============
#Print the results
#============
print(
    filtered_df[["Name", "Attack", "Speed", "Defense", "Atk + Spd + Def"]]
)
#====================
#Define which type has bigger max value and print the results
#====================
if max(filtered_df['Type 1'].value_counts().sum() > max(filtered_df['Type 2'].value_counts().sum()): 
    print(filtered_df['Type 1'].value_counts())
else:
    print(filtered_df['Type 2'].value_counts().sum())
print(filtered_df['Type 1'].value_counts().sum())

Average:
-----------------------------
Attack              79.00125
Speed               68.27750
Defense             73.84250
Atk + Spd + Def    290.38000
dtype: float64
-----------------------------
                          Name  Attack  Speed  Defense  Atk + Spd + Def
2                     Venusaur      82     80       83              325
3        VenusaurMega Venusaur     100     80      123              383
6                    Charizard      84    100       78              340
7    CharizardMega Charizard X     130    100      111              419
8    CharizardMega Charizard Y     104    100       78              360
..                         ...     ...    ...      ...              ...
792                    Xerneas     131     99       95              451
793                    Yveltal     131     99       95              451
794           Zygarde50% Forme     100     95      121              424
796        DiancieMega Diancie     160    110      110              430
799     

Super bonus: There are many platforms out there that contain different tools to boost your learning. Then for the super bonus create an account on [kaggle](https://www.kaggle.com/) and complete the courses
[intro to programming](https://www.kaggle.com/learn/intro-to-programming) and [intro to python](https://www.kaggle.com/learn/python) courses. All kaggle courses are free of charge and offer a [certificate](https://www.kaggle.com/learn-course-certificates) !

In [ ]:


#Subscribed



